# Generated by Django 4.0.1 on 2022-03-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amchurch', '0003_portfolio_body_portfolio_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='app_image')),
            ],
        ),
        migrations.CreateModel(
            name='Wep1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='web1_image')),
            ],
        ),
        migrations.CreateModel(
            name='Weps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='web_image')),
            ],
        ),
    ]
