# Generated by Django 4.0.1 on 2022-03-19 09:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amchurch', '0004_apps_wep1_weps'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='Desc',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='wep1',
            name='Desc',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='weps',
            name='Desc',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
