# Generated by Django 4.0.1 on 2022-04-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amchurch', '0007_goals_objectives_alter_apps_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='Objectives',
            new_name='Objective',
        ),
    ]
