# Generated by Django 4.0.1 on 2022-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogImae',
            field=models.ImageField(default='image', upload_to='blogImages /%Y/% m/% d/'),
        ),
    ]
