# Generated by Django 4.0.1 on 2022-02-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_blogimae_post_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogImage',
            field=models.ImageField(blank=True, null=True, upload_to='blogImages'),
        ),
    ]
