# Generated by Django 4.0.1 on 2022-02-25 00:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideImage', models.ImageField(upload_to='sliderPics')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField(blank=b'I01\n', null=b'I01\n')),
            ],
        ),
    ]
