# Generated by Django 4.0.1 on 2022-04-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='',
        ),
    ]
